name: Swap

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: judite
          POSTGRES_USER: judite
          POSTGRES_PASSWORD: judite

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        extensions: gd, bcmath, ctype, json, openssl, tokenizer, xml, mbstring, intl, imagick, redis, pdo, pgsql
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Migrate database
      run: php artisan migrate
    - name: Prepare database data
      run: php artisan db:seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
